# Generated by Django 4.1 on 2022-11-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Opens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='uploadedFile',
        ),
    ]
