# Generated by Django 4.1 on 2022-11-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Opens', '0002_remove_documento_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
